# Generated by Django 4.2.7 on 2025-09-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='poll',
            name='polls_poll_is_acti_5cfcc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='poll',
            name='polls_poll_created_3f3b19_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_user_id_1ac8c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_option__9fc1fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_user_se_aba581_idx',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='poll',
            name='allows_multiple_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter')},
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_session',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
